# Generated by Django 4.1.3 on 2023-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titular', models.CharField(max_length=70)),
                ('tipo', models.IntegerField()),
                ('saldo', models.FloatField()),
                ('banco', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_origem', models.CharField(max_length=10)),
                ('conta_destino', models.CharField(max_length=10)),
                ('valor', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
            ],
        ),
    ]
